#!/bin/sh
cd "${0%/*}/../.." || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove surface and features
rm -rf constant/triSurface/*
rm -rf constant/extendedFeatureEdgeMesh
rm -rf dynamicCode
rm -rf logs/*

find ./constant -mindepth 1 -maxdepth 1 \
    ! -name "triSurface" \
    ! -name "transportProperties" \
    ! -name "turbulenceProperties" \
    -exec rm -rf {} +

find . -mindepth 1 -maxdepth 1 \
    ! -name "*.sh" \
    ! -name "__All*" \
    ! -name ".git" \
    ! -name "0.orig" \
    ! -name "system" \
    ! -name "constant" \
    ! -name "logs" \
    ! -name "scripts" \
    -exec rm -rf {} +


#------------------------------------------------------------------------------
